# **Decision Tree & Random Forest Classifier — Practice Notebook**

Datasets: **Iris** and **Tips** (from the Seaborn library)

For each dataset, you will:
1. Build a Decision Tree Classifier
2. Build a Random Forest Classifier
3. Generate the Classification Report, Confusion Matrix, and Accuracy Score for both
4. Compare the accuracy of the two models

Write your code in the empty cells below each question.

## **Part A: Iris Dataset**

Target variable: `species` (3 classes)

**Q1.** Import the required libraries and load the `iris` dataset from Seaborn. Display the first 5 rows.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

data = sns.load_dataset('iris')
data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

**Q2.** Check the shape of the dataset, data types, and confirm there are no missing values.

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

**Q3.** Define the independent variables `X` (all feature columns) and the dependent variable `y` (`species`).

In [42]:
X_iris = data.drop('species', axis=1)
y_iris = data['species']

**Q4.** Split the dataset into training and testing sets.

In [44]:
from sklearn.model_selection import train_test_split
X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(X_iris, y_iris, test_size=0.2, random_state=42)

In [45]:
X_train_iris

     sepal_length  sepal_width  petal_length  petal_width
22            4.6          3.6           1.0          0.2
15            5.7          4.4           1.5          0.4
65            6.7          3.1           4.4          1.4
11            4.8          3.4           1.6          0.2
42            4.4          3.2           1.3          0.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[120 rows x 4 columns]

In [46]:
y_train_iris

22         setosa
15         setosa
65     versicolor
11         setosa
42         setosa
          ...
71     versicolor
106     virginica
14         setosa
92     versicolor
102     virginica
Name: species, Length: 120, dtype: object

### Decision Tree Classifier — Iris

**Q5.** Build a Decision Tree Classifier and train it on the training data.

In [47]:
from sklearn.tree import DecisionTreeClassifier
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(X_train_iris, y_train_iris)

DecisionTreeClassifier(criterion='entropy', random_state=0)

**Q6.** Predict the `species` for the test set.

In [50]:
y_pred_iris= classifier.predict(X_test_iris)

**Q7.** Generate and print the Classification Report for the Decision Tree model.

In [51]:
from sklearn.metrics import classification_report

print("Classification Report for Decision Tree Model:")
print(classification_report(y_test_iris, y_pred_iris))

Classification Report for Decision Tree Model:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

**Q8.** Generate and print the Confusion Matrix for the Decision Tree model.

In [53]:
from sklearn.metrics import confusion_matrix
dt_cm_iris = confusion_matrix(y_test_iris, y_pred_iris)
print("Confusion Matrix for Decision Tree Model:")
print(dt_cm_iris)

Confusion Matrix for Decision Tree Model:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

**Q9.** Calculate and print the Accuracy Score for the Decision Tree model.

In [55]:
from sklearn.metrics import accuracy_score
dt_accuracy_iris = accuracy_score(y_test_iris, y_pred_iris)
print("Accuracy of Decision Tree Model:", dt_accuracy_iris)

Accuracy of Decision Tree Model: 1.0

### Random Forest Classifier — Iris

**Q10.** Build a Random Forest Classifier and train it on the training data.

In [57]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train_iris, y_train_iris)

RandomForestClassifier(random_state=42)

**Q11.** Predict the `species` for the test set.

In [59]:
y_pred_rf_iris = rf.predict(X_test_iris)

**Q12.** Generate and print the Classification Report for the Random Forest model.

In [60]:
from sklearn.metrics import classification_report
print("Classification Report for Random Forest Model:")
print(classification_report(y_test_iris, y_pred_rf_iris))

Classification Report for Random Forest Model:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

**Q13.** Generate and print the Confusion Matrix for the Random Forest model.

In [61]:
from sklearn.metrics import confusion_matrix
rf_cm_iris = confusion_matrix(y_test_iris, y_pred_rf_iris)
print("Confusion Matrix for Random Forest Model:")
print(rf_cm_iris)

Confusion Matrix for Random Forest Model:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

**Q14.** Calculate and print the Accuracy Score for the Random Forest model.

In [62]:
from sklearn.metrics import accuracy_score
rf_accuracy_iris = accuracy_score(y_test_iris, y_pred_rf_iris)
print("Accuracy of Random Forest Model:", rf_accuracy_iris)

Accuracy of Random Forest Model: 1.0

**Q15.** Compare the accuracy scores of the Decision Tree and Random Forest models on the Iris dataset. Which model performed better, and by how much?

In [82]:
difference = abs(rf_accuracy_iris - dt_accuracy_iris) * 100

if dt_accuracy_iris > rf_accuracy_iris:
    print(f"Decision Tree performed better by {difference:.2f}%")
elif rf_accuracy_iris > dt_accuracy_iris:
    print(f"Random Forest performed better by {difference:.2f}%")
else:
    print("Both models performed equally.")

Both models performed equally.

## **Part B: Tips Dataset**

Target variable: `time` (2 classes — Lunch/Dinner)

**Q16.** Load the `tips` dataset from Seaborn. Display the first 5 rows.

In [18]:
data_tips = sns.load_dataset('tips')
data_tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

**Q17.** Check the shape of the dataset, data types, and confirm there are no missing values.

In [19]:
data_tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

**Q18.** Identify the categorical columns in the dataset and encode them into numeric form so they can be used as model inputs.

In [20]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data_tips['sex_encoded'] = le.fit_transform(data_tips['sex'])
data_tips['smoker_encoded'] = le.fit_transform(data_tips['smoker'])
data_tips['day_encoded'] = le.fit_transform(data_tips['day'])
data_tips['time_encoded'] = le.fit_transform(data_tips['time'])

data_tips

,total_bill,tip,sex,smoker,day,time,size,sex_encoded,smoker_encoded,day_encoded,time_encoded
0,16.99,1.01,Female,No,Sun,Dinner,2,0,0,2,0
1,10.34,1.66,Male,No,Sun,Dinner,3,1,0,2,0
2,21.01,3.50,Male,No,Sun,Dinner,3,1,0,2,0
3,23.68,3.31,Male,No,Sun,Dinner,2,1,0,2,0
4,24.59,3.61,Female,No,Sun,Dinner,4,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,1,0,1,0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,0,1,1,0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,1,1,1,0
242,17.82,1.75,Male,No,Sat,Dinner,2,1,0,1,0
243,18.78,3.00,Female,No,Thur,Dinner,2,0,0,3,0

**Q19.** Define the independent variables `X` (all relevant feature columns) and the dependent variable `y` (`time`).

In [65]:
X_tips = data_tips[['total_bill', 'tip', 'sex_encoded','smoker_encoded', 'day_encoded', 'size']]
y_tips = data_tips['time_encoded']

**Q20.** Split the dataset into training and testing sets.

In [66]:
from sklearn.model_selection import train_test_split
X_train_tips, X_test_tips, y_train_tips, y_test_tips = train_test_split(X_tips, y_tips, test_size=0.2, random_state=42)

In [67]:
X_train_tips

     total_bill   tip  sex_encoded  smoker_encoded  day_encoded  size
228       13.28  2.72            1               0            1     2
208       24.27  2.03            1               1            1     2
96        27.28  4.00            1               1            0     2
167       31.71  4.50            1               0            2     4
84        15.98  2.03            1               0            3     2
..          ...   ...          ...             ...          ...   ...
106       20.49  4.06            1               1            1     2
14        14.83  3.02            0               0            2     2
92         5.75  1.00            0               1            0     2
179       34.63  3.55            1               1            2     2
102       44.30  2.50            0               1            1     3

[195 rows x 6 columns]

In [68]:
y_train_tips

228    0
208    0
96     0
167    0
84     1
      ..
106    0
14     0
92     0
179    0
102    0
Name: time_encoded, Length: 195, dtype: int64

### Decision Tree Classifier — Tips

**Q21.** Build a Decision Tree Classifier and train it on the training data.

In [69]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion='entropy', random_state=42)
clf.fit(X_train_tips, y_train_tips)

DecisionTreeClassifier(criterion='entropy', random_state=42)

**Q22.** Predict `time` for the test set.

In [70]:
y_pred_tips = clf.predict(X_test_tips)

**Q23.** Generate and print the Classification Report for the Decision Tree model.

In [71]:
from sklearn.metrics import classification_report
print("Classification Report for Decision Tree Model on Tips Dataset:")
print(classification_report(y_test_tips, y_pred_tips))

Classification Report for Decision Tree Model on Tips Dataset:
              precision    recall  f1-score   support

           0       0.94      0.97      0.96        34
           1       0.93      0.87      0.90        15

    accuracy                           0.94        49
   macro avg       0.94      0.92      0.93        49
weighted avg       0.94      0.94      0.94        49

**Q24.** Generate and print the Confusion Matrix for the Decision Tree model.

In [73]:
from sklearn.metrics import confusion_matrix
dt_cm_tips = confusion_matrix(y_test_tips, y_pred_tips)
print("Confusion Matrix for Decision Tree Model on Tips Dataset:")
print(dt_cm_tips)

Confusion Matrix for Decision Tree Model on Tips Dataset:
[[33  1]
 [ 2 13]]

**Q25.** Calculate and print the Accuracy Score for the Decision Tree model.

In [74]:
from sklearn.metrics import accuracy_score
dt_accuracy_tips = accuracy_score(y_test_tips, y_pred_tips)
print("Accuracy of Decision Tree Model on Tips Dataset:", dt_accuracy_tips)

Accuracy of Decision Tree Model on Tips Dataset: 0.9387755102040817

### Random Forest Classifier — Tips

**Q26.** Build a Random Forest Classifier and train it on the training data.

In [75]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(criterion='entropy',random_state=42)
rf_model.fit(X_train_tips, y_train_tips)

RandomForestClassifier(criterion='entropy', random_state=42)

**Q27.** Predict `time` for the test set.

In [76]:
y_pred_rf_tips = rf_model.predict(X_test_tips)

**Q28.** Generate and print the Classification Report for the Random Forest model.

In [77]:
from sklearn.metrics import classification_report

print("Classification Report for Random Forest Model on Tips Dataset:")
print(classification_report(y_test_tips, y_pred_rf_tips))

Classification Report for Random Forest Model on Tips Dataset:
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        34
           1       0.88      1.00      0.94        15

    accuracy                           0.96        49
   macro avg       0.94      0.97      0.95        49
weighted avg       0.96      0.96      0.96        49

**Q29.** Generate and print the Confusion Matrix for the Random Forest model.

In [78]:
from sklearn.metrics import confusion_matrix
rf_cm_tips = confusion_matrix(y_test_tips, y_pred_rf_tips)
print("Confusion Matrix for Random Forest Model on Tips Dataset:")
print(rf_cm_tips)

Confusion Matrix for Random Forest Model on Tips Dataset:
[[32  2]
 [ 0 15]]

**Q30.** Calculate and print the Accuracy Score for the Random Forest model.

In [79]:
from sklearn.metrics import accuracy_score
rf_accuracy_tips = accuracy_score(y_test_tips, y_pred_rf_tips)
print("Accuracy of Random Forest Model on Tips Dataset:", rf_accuracy_tips)

Accuracy of Random Forest Model on Tips Dataset: 0.9591836734693877

**Q31.** Compare the accuracy scores of the Decision Tree and Random Forest models on the Tips dataset. Which model performed better, and by how much?

In [83]:
difference_tips = abs(rf_accuracy_tips - dt_accuracy_tips) * 100

if dt_accuracy_tips > rf_accuracy_tips:
    print(f"Decision Tree performed better on Tips Dataset by {difference_tips:.2f}%")

elif rf_accuracy_tips > dt_accuracy_tips:
    print(f"Random Forest performed better on Tips Dataset by {difference_tips:.2f}%")

else:
    print("Both models performed equally on Tips Dataset.")

Random Forest performed better on Tips Dataset by 2.04%

## **Final Comparison**

**Q32.** Summarize the accuracy scores of all four models (Decision Tree – Iris, Random Forest – Iris, Decision Tree – Tips, Random Forest – Tips) in a single table or DataFrame. Which dataset-model combination performed best overall?

In [91]:
accuracy_df = pd.DataFrame({
    'Dataset': ['Iris', 'Iris', 'Tips', 'Tips'],
    'Model': [
        'Decision Tree',
        'Random Forest',
        'Decision Tree',
        'Random Forest'
    ],
    'Accuracy': [
        dt_accuracy_iris,
        rf_accuracy_iris,
        dt_accuracy_tips,
        rf_accuracy_tips
    ]
})

accuracy_df['Accuracy (%)'] = accuracy_df['Accuracy'] * 100
print(accuracy_df)

best_model = accuracy_df.iloc[0]

print("\nBest-performing combination overall:")
print(f"Dataset: {best_model['Dataset']}")
print(f"Model: {best_model['Model']}")
print(f"Accuracy: {best_model['Accuracy (%)']:.2f}%")

  Dataset          Model  Accuracy  Accuracy (%)
0    Iris  Decision Tree  1.000000    100.000000
1    Iris  Random Forest  1.000000    100.000000
2    Tips  Decision Tree  0.938776     93.877551
3    Tips  Random Forest  0.959184     95.918367

Best-performing combination overall:
Dataset: Iris
Model: Decision Tree
Accuracy: 100.00%